<?php
/**
 * Yii core class map.
 * This file is automatically generated by the "build classmap" command under the "build" folder.
 * Do not modify it directly.
 * @link      http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license   http://www.yiiframework.com/license/
 */
return [
    'likingfit\Workflow\Workflow' => __DIR__.'/Workflow/Workflow.php',
    /**
     * Base
     */
    'likingfit\Workflow\Base\Activity' => __DIR__.'/Workflow/Base/Activity.php',
    'likingfit\Workflow\Base\Node' => __DIR__.'/Workflow/Base/Node.php',
    'likingfit\Workflow\Base\Element' => __DIR__.'/Workflow/Base/Element.php',
    'likingfit\Workflow\Base\Object' => __DIR__.'/Workflow/Base/Object.php',
    'likingfit\Workflow\Base\Edge' => __DIR__.'/Workflow/Base/Edge.php',
    'likingfit\Workflow\Base\Synchronizer' => __DIR__.'/Workflow/Base/Synchronizer.php',
    'likingfit\Workflow\Base\Token' => __DIR__.'/Workflow/Base/Token.php',
    'likingfit\Workflow\Base\Transition' => __DIR__.'/Workflow/Base/Transition.php',
    'likingfit\Workflow\Base\Loop' => __DIR__.'/Workflow/Base/Loop.php',
    'likingfit\Workflow\Base\Task' => __DIR__.'/Workflow/Base/Task.php',
    'likingfit\Workflow\Base\WorkItem' => __DIR__.'/Workflow/Base/WorkItem.php',
    'likingfit\Workflow\Base\Net' => __DIR__.'/Workflow/Base/Net.php',
    'likingfit\Workflow\Base\Process' => __DIR__.'/Workflow/Base/Process.php',
    'likingfit\Workflow\Base\TaskInstance' => __DIR__.'/Workflow/Base/TaskInstance.php',
    'likingfit\Workflow\Base\DataField' => __DIR__.'/Workflow/Base/DataField.php',
    'likingfit\Workflow\Base\TemplateProcess' => __DIR__.'/Workflow/Base/TemplateProcess.php',
    'likingfit\Workflow\Base\Graph' => __DIR__.'/Workflow/Base/Graph.php',
    /**
     * Util
     */
    'likingfit\Workflow\Util\PersistenceService' => __DIR__.'/Workflow/Util/PersistenceService.php',
    'likingfit\Workflow\Util\ConditionService' => __DIR__.'/Workflow/Util/ConditionService.php',
    'likingfit\Workflow\Util\LogService' => __DIR__.'/Workflow/Util/LogService.php',
    'likingfit\Workflow\Util\FlowException' => __DIR__.'/Workflow/Util/FlowException.php',
    'likingfit\Workflow\Util\LockService' => __DIR__.'/Workflow/Util/LockService.php',
    'likingfit\Workflow\Util\EventService' => __DIR__.'/Workflow/Util/EventService.php',
    /**
     * Parser
     */
    'likingfit\Workflow\Parser\Parser' => __DIR__.'/Workflow/Parser/Parser.php',
    'likingfit\Workflow\Parser\EntityNames' => __DIR__.'/Workflow/Parser/EntityNames.php',
    /**
     * Exception
     */
    'likingfit\Workflow\Exception\ParseException' => __DIR__.'/Workflow/Exception/ParseException.php',
    'likingfit\Workflow\Exception\ProcessException' => __DIR__.'/Workflow/Exception/ProcessException.php',
    'likingfit\Workflow\Exception\FlowException' => __DIR__.'/Workflow/Exception/FlowException.php',
];
